version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elixer_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - elixer-network

  webserver:
    image: nginx:alpine
    container_name: elixer_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elixer-network

  db:
    image: mysql:8.0
    container_name: elixer_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: elixer_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - elixer-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: elixer_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - elixer-network
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: elixer_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - elixer-network

networks:
  elixer-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

