<?php



return [



    'settings' => [
        'table' => 'settings',
        'route' => 'settings',
        'full_route_name' => 'settings',
        'singular_name' => 'Setting',
        'plural_name' => 'Settings',
        'singular_key' => 'setting',
        'plural_key' => 'settings',
        'view_path' => 'CP.settings.',
        'id_field' => 'id',
        // 'controller' => SettingController::class,
        'upload_path' => 'settings',
        'permissions' => [
            'view' => 'view_settings',
            'add' => 'create_settings',
            'edit' => 'edit_settings',
            'delete' => 'delete_settings',
        ],
        'children' => [
            'general' => [
                'route' => 'general',
                'full_route_name' => 'settings.general',
                'singular_name' => 'General Setting',
                'singular_key' => 'general_setting',

                'plural_name' => 'General Settings',
                'view_path' => 'CP.settings.general.',
                'controller' => \App\Http\Controllers\CP\Settings\GeneralSettingController::class,
                'permissions' => [
                    'view' => 'view_general_settings',
                    'edit' => 'edit_general_settings',
                ],
            ],



        ],
    ],

    'about_office' => [
        'table' => 'about_office',
        'route' => 'about_office',
        'full_route_name' => 'about_office',
        'singular_name' => 'About Office',
        'plural_name' => 'About Office',
        'singular_key' => 'about_office',
        'plural_key' => 'about_office',
        'view_path' => 'CP.about_office.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\AboutOfficeController::class,
        'upload_path' => 'about_office',
        'permissions' => [
            'view' => 'view_about_office',
            'create' => 'create_about_office',
            'edit' => 'edit_about_office',
            'delete' => 'delete_about_office',
        ],
    ],
    'our_story' => [
        'table' => 'our_story',
        'route' => 'our_story',
        'full_route_name' => 'our_story',
        'singular_name' => 'Our Story',
        'plural_name' => 'Our Story',
        'singular_key' => 'our_story',
        'plural_key' => 'our_story',
        'view_path' => 'CP.our_story.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\OurStoryController::class,
        'upload_path' => 'our_story',
        'permissions' => [
            'view' => 'view_our_story',
            'create' => 'create_our_story',
            'edit' => 'edit_our_story',
            'delete' => 'delete_our_story',
        ],
    ],


    'categories' => [
        'table' => 'categories',
        'route' => 'categories',
        'full_route_name' => 'categories',
        'singular_name' => 'Category',
        'plural_name' => 'Categories',
        'singular_key' => 'category',
        'plural_key' => 'categories',
        'view_path' => 'CP.categories.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\CategoryController::class,
        'upload_path' => 'categories',
        'permissions' => [
            'view' => 'view_categories',
            'create' => 'create_categories',
            'edit' => 'edit_categories',
            'delete' => 'delete_categories',
        ],
    ],
    'contact_us' => [
        'table' => 'contact_us',
        'route' => 'contact_us',
        'full_route_name' => 'contact_us',
        'singular_name' => 'Contact Us',
        'plural_name' => 'Contact Us',
        'singular_key' => 'contact_us',
        'plural_key' => 'contact_us',
        'view_path' => 'CP.contact_us.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\ContactUsController::class,
        'upload_path' => 'contact_us',
        'permissions' => [
            'view' => 'view_contact_us',
            'create' => 'create_contact_us',
            'edit' => 'edit_contact_us',
            'delete' => 'delete_contact_us',
        ],
    ],
    'real_results' => [
        'table' => 'real_results',
        'route' => 'real_results',
        'full_route_name' => 'real_results',
        'singular_name' => 'Real Result',
        'plural_name' => 'Real Results',
        'singular_key' => 'real_result',
        'plural_key' => 'real_results',
        'view_path' => 'CP.real_results.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\RealResultController::class,
        'upload_path' => 'real_results',
        'permissions' => [
            'view' => 'view_real_results',
            'create' => 'create_real_results',
            'edit' => 'edit_real_results',
            'delete' => 'delete_real_results',
        ],
    ],

    'faq' => [
        'table' => 'faq',
        'route' => 'faq',
        'full_route_name' => 'faq',
        'singular_name' => 'FAQ',
        'plural_name' => 'FAQs',
        'singular_key' => 'faq',
        'plural_key' => 'faqs',
        'view_path' => 'CP.faqs.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\FAQController::class,
        'upload_path' => 'faqs',
        'permissions' => [
            'view' => 'view_faqs',
            'create' => 'create_faqs',
            'edit' => 'edit_faqs',
            'delete' => 'delete_faqs',
        ],
    ],
    'attachments' => [
        'table' => 'attachments',
        'route' => 'attachments',
        'full_route_name' => 'attachments',
        'singular_name' => 'Attachment',
        'plural_name' => 'Attachments',
        'singular_key' => 'attachment',
        'plural_key' => 'attachments',
        'view_path' => 'CP.attachments.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\Attachments\AttachmentController::class,
        'upload_path' => 'attachments',
        'permissions' => [
            'view' => 'view_attachments',
            'create' => 'create_attachments',
            'edit' => 'edit_attachments',
            'delete' => 'delete_attachments',
        ],
    ],
    'addresses' => [
        'table' => 'addresses',
        'route' => 'addresses',
        'full_route_name' => 'addresses',
        'singular_name' => 'Address',
        'plural_name' => 'Addresses',
        'singular_key' => 'address',
        'plural_key' => 'addresses',
        'view_path' => 'CP.addresses.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\AddressController::class,
        'upload_path' => 'addresses',
        'permissions' => [
            'view' => 'view_addresses',
            'create' => 'create_addresses',
            'edit' => 'edit_addresses',
            'delete' => 'delete_addresses',
        ],
    ],
    'coupons' => [
        'table' => 'coupons',
        'route' => 'coupons',
        'full_route_name' => 'coupons',
        'singular_name' => 'Coupon',
        'plural_name' => 'Coupons',
        'singular_key' => 'coupon',
        'plural_key' => 'coupons',
        'view_path' => 'CP.coupons.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\CouponController::class,
        'upload_path' => 'coupons',
        'permissions' => [
            'view' => 'view_coupons',
            'create' => 'create_coupons',
            'edit' => 'edit_coupons',
            'delete' => 'delete_coupons',
        ],
    ],
    'products' => [
        'table' => 'products',
        'route' => 'products',
        'full_route_name' => 'products',
        'singular_name' => 'Product',
        'plural_name' => 'Products',
        'singular_key' => 'product',
        'plural_key' => 'products',
        'view_path' => 'CP.products.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\ProductController::class,
        'upload_path' => 'products',
        'permissions' => [
            'view' => 'view_products',
            'create' => 'create_products',
            'edit' => 'edit_products',
            'delete' => 'delete_products',
        ],
    ],
    'orders' => [
        'table' => 'orders',
        'route' => 'orders',
        'full_route_name' => 'orders',
        'singular_name' => 'Order',
        'plural_name' => 'Orders',
        'singular_key' => 'order',
        'plural_key' => 'orders',
        'view_path' => 'CP.orders.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\Order\OrderController::class,
        'upload_path' => 'orders',
        'permissions' => [
            'view' => 'view_orders',
            'create' => 'create_orders',
            'edit' => 'edit_orders',
            'delete' => 'delete_orders',
        ],
        'children' => [
            'order_items' => [
                'table' => 'order_items',
                'route' => 'order_items',
                'full_route_name' => 'orders.order_items',
                'singular_name' => 'Order Item',
                'plural_name' => 'Order Items',
                'singular_key' => 'order_item',
                'plural_key' => 'order_items',
                'view_path' => 'CP.orders.tabs.order_items.',
                'id_field' => 'id',
                'controller' => \App\Http\Controllers\CP\Order\OrderItemController::class,
                'upload_path' => 'order_items',
                'permissions' => [
                    'view' => 'view_order_items',
                    'create' => 'create_order_items',
                    'edit' => 'edit_order_items',
                    'delete' => 'delete_order_items',
                ],

            ]
        ]
    ],



    'sliders' => [
        'table' => 'sliders',
        'route' => 'sliders',
        'full_route_name' => 'sliders',
        'singular_name' => 'Slider',
        'plural_name' => 'Sliders',
        'singular_key' => 'slider',
        'plural_key' => 'sliders',
        'view_path' => 'CP.sliders.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\SliderController::class,
        'upload_path' => 'sliders',
        'permissions' => [
            'view' => 'view_sliders',
            'create' => 'create_sliders',
            'edit' => 'edit_sliders',
            'delete' => 'delete_sliders',
        ],
    ],



    'why_choose_us' => [
        'table' => 'why_choose_us',
        'route' => 'why_choose_us',
        'full_route_name' => 'why_choose_us',
        'singular_name' => 'Why Choose Us',
        'plural_name' => 'Why Choose Us',
        'singular_key' => 'why_choose_us',
        'plural_key' => 'why_choose_us',
        'view_path' => 'CP.why_choose_us.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\WhyChooseUsController::class,
        'upload_path' => 'why_choose_us',
        'permissions' => [
            'view' => 'view_why_choose_us',
            'create' => 'create_why_choose_us',
            'edit' => 'edit_why_choose_us',
            'delete' => 'delete_why_choose_us',
        ],
    ],
    'customer_rates' => [
        'table' => 'customer_rates',
        'route' => 'customer_rates',
        'full_route_name' => 'customer_rates',
        'singular_name' => 'Customer Rate',
        'plural_name' => 'Customer Rates',
        'singular_key' => 'customer_rate',
        'plural_key' => 'customer_rates',
        'view_path' => 'CP.customer_rates.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\CustomerRateController::class,
        'upload_path' => 'customer_rates',
        'permissions' => [
            'view' => 'view_customer_rates',
            'create' => 'create_customer_rates',
            'edit' => 'edit_customer_rates',
            'delete' => 'delete_customer_rates',
        ],
    ],
    'how_we_works' => [
        'table' => 'how_we_works',
        'route' => 'how_we_works',
        'full_route_name' => 'how_we_works',
        'singular_name' => 'How We Work',
        'plural_name' => 'How We Works',
        'singular_key' => 'how_we_work',
        'plural_key' => 'how_we_works',
        'view_path' => 'CP.how_we_works.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\HowWeWorkController::class,
        'upload_path' => 'how_we_works',
        'permissions' => [
            'view' => 'view_how_we_works',
            'create' => 'create_how_we_works',
            'edit' => 'edit_how_we_works',
            'delete' => 'delete_how_we_works',
        ],
    ],
    'articles_types' => [
        'table' => 'articles_types',
        'route' => 'articles_types',
        'full_route_name' => 'articles_types',
        'singular_name' => 'Article Type',
        'plural_name' => 'Article Types',
        'singular_key' => 'article_type',
        'plural_key' => 'articles_types',
        'view_path' => 'CP.articles_types.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\ArticleTypeController::class,
        'upload_path' => 'articles_types',
        'permissions' => [
            'view' => 'view_articles_types',
            'create' => 'create_articles_types',
            'edit' => 'edit_articles_types',
            'delete' => 'delete_articles_types',
        ],
    ],
    'articles' => [
        'table' => 'articles',
        'route' => 'articles',
        'full_route_name' => 'articles',
        'singular_name' => 'Article',
        'plural_name' => 'Articles',
        'singular_key' => 'article',
        'plural_key' => 'articles',
        'view_path' => 'CP.articles.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\ArticleController::class,
        'upload_path' => 'articles',
        'permissions' => [
            'view' => 'view_articles',
            'create' => 'create_articles',
            'edit' => 'edit_articles',
            'delete' => 'delete_articles',
        ],
        'children' => [
            'article_contents' => [
                'table' => 'article_contents',
                'route' => 'article_contents',
                'full_route_name' => 'articles.article_contents',
                'singular_name' => 'Article Content',
                'plural_name' => 'Article Contents',
                'singular_key' => 'article_content',
                'plural_key' => 'article_contents',
                'view_path' => 'CP.articles.tabs.article_contents.',
                'id_field' => 'id',
                'controller' => \App\Http\Controllers\CP\ArticleContentController::class,
                'upload_path' => 'article_contents',
                'permissions' => [
                    'view' => 'view_article_contents',
                    'create' => 'create_article_contents',
                    'edit' => 'edit_article_contents',
                    'delete' => 'delete_article_contents',
                ],

            ]
        ]
    ],

    'services' => [
        'table' => 'services',
        'route' => 'services',
        'full_route_name' => 'services',
        'singular_name' => 'Service',
        'plural_name' => 'Services',
        'singular_key' => 'service',
        'plural_key' => 'services',
        'view_path' => 'CP.services.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\ServiceController::class,
        'upload_path' => 'services',
        'permissions' => [
            'view' => 'view_services',
            'create' => 'create_services',
            'edit' => 'edit_services',
            'delete' => 'delete_services',
        ],
    ],

    'sucess_stories' => [
        'table' => 'sucess_stories',
        'route' => 'sucess_stories',
        'full_route_name' => 'sucess_stories',
        'singular_name' => 'Sucess Story',
        'plural_name' => 'Sucess Stories',
        'singular_key' => 'sucess_story',
        'plural_key' => 'sucess_stories',
        'view_path' => 'CP.sucess_stories.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\SucessStoryController::class,
        'upload_path' => 'sucess_stories',
        'permissions' => [
            'view' => 'view_sucess_stories',
            'create' => 'create_sucess_stories',
            'edit' => 'edit_sucess_stories',
            'delete' => 'delete_sucess_stories',
        ],
    ],
    'videos' => [
        'table' => 'videos',
        'route' => 'videos',
        'full_route_name' => 'videos',
        'singular_name' => 'Video',
        'plural_name' => 'Videos',
        'singular_key' => 'video',
        'plural_key' => 'videos',
        'view_path' => 'CP.videos.',
        'id_field' => 'id',
        'controller' => \App\Http\Controllers\CP\VideoController::class,
        'upload_path' => 'videos',
        'permissions' => [
            'view' => 'view_videos',
            'create' => 'create_videos',
            'edit' => 'edit_videos',
            'delete' => 'delete_videos',
        ],
    ],

];
